### PR TITLE
Devex: Upgrade Github Action Helper Packages

### PR DESCRIPTION
**Pull request by rachelschneiderman**
I noticed this warning in a recent run of the smoketests: 

image

This PR upgrades the packages the warning mentions.

### CODE REVIEW

**Comment by jimlerza** [comment]
Should this be done each week along with dependency updates?

**Comment by rachelschneiderman** [comment]
> Should this be done each week along with dependency updates?

They could be!

**Review by zachrog — APPROVED** [review]

**Review by mmarcotte — APPROVED** [review]

**Comment by jimlerza** [comment]
> > Should this be done each week along with dependency updates?
> 
> They could be!

Does this merit inclusion in the dependency updates documentation?

**Review by jimlerza — APPROVED** [review]

**Comment by rachelschneiderman** [comment]
> > > Should this be done each week along with dependency updates?
> > 
> > 
> > They could be!
> 
> Does this merit inclusion in the dependency updates documentation?

Looking at the release cadence, a major version release happens about every 18 months. I am happy to add them to the docs if you think that would be useful! I didn't originally add it to the dependency updates documentation as I didn't want folks to get bogged down checking something every week that isn't updated all that often.

**Pull request merged**
