### PR TITLE
Backmerge to test automation

### PR DESCRIPTION
**Pull request by rosiehsmith**
A little something to automate the backmerge from `staging` to `test` to hopefully make life easier! 🤸 

This github action checks for closed, merged branches into the `staging` branch and kicks off a github action that automates backmerging into the `test` branch.

Successful test of this: made a PR https://github.com/flexion/ef-cms/pull/9849 from `feature-branch-to-stg` into `staging-temp`, which triggered an automated github action to backmerge into `test-temp` https://github.com/flexion/ef-cms/actions/runs/4257356099

But, what if there are merge conflicts? 😭 The PR run will fail, and we should get emailed that it failed. ✅ I tested this out here on this PR https://github.com/flexion/ef-cms/pull/9851, resulting into this PR run failure https://github.com/flexion/ef-cms/actions/runs/4257515364/jobs/7407728056

Open to feedback on if this is helpful! It's probably worth changing out the user.email and user.name as well 😄

### CODE REVIEW

**Comment by shumway-tm** [comment]
🔥! 🚀🚀🚀

**Review by rgoshen — COMMENTED** [review]
This would be awesome.  Not knowing much about github actions, who would be setup to receive the emails upon failure or is there a way to have everyone on the team notified of the failure?

**Comment by rosiehsmith** [comment]
> This would be awesome. Not knowing much about github actions, who would be setup to receive the emails upon failure or is there a way to have everyone on the team notified of the failure?

> Good question! I'm a little hazy here too. Based on [docs](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs), it says you'll be emailed if you "subscribe to notifications about workflow runs that you trigger" so to me that seems like whoever merges the feature branch into `staging`. In my forced merge failure test, I got the notification, and I assume that's because I merged the feature branch. I could test this by opening that PR again and someone else merges it instead of me to see who the email goes to.

If anyone else is curious, Rick and I confirmed that whoever merges it gets the PR Run failure notification.

**Review by rgoshen — APPROVED** [review]

**Review by rachelschneiderman — APPROVED** [review]
WOW

**Review by zachrog — APPROVED** [review]
WHOAH. Love the idea.

**Pull request merged**
