### PR TITLE
DevEx - 1102 clean up security

### PR DESCRIPTION
**Pull request by codyseibert**
allowing the viewer protocol policy to be configured via aws secrets due to a suggestion from the Flexion security team not wanting http accessible.  This should not affect the court's environments since it fallback to the normal redirect-to-https setting

### CODE REVIEW

**Review by rachelschneiderman — APPROVED** [review]
Looks great! Thanks for doing this! Quick question, it makes sense that this wouldn't affect any of the court's envs because of the default value, has this been deployed on to an exp just to verify that?

**Comment by codyseibert** [comment]
@rachelschneiderman yeah I've been trying to deploy this to exp2 using the default value, but I can't tell if the exp2 is broken or if this change breaks it... I'll update if I figure out what's going on.  I may just switch to exp3 since maybe exp2 is in a bad state?

**Comment by rachelschneiderman** [comment]
@codyseibert Makes sense to me! Thanks for doing that!

**Comment by codyseibert** [comment]
@rachelschneiderman this was just deployed successfully to exp3. https://app.circleci.com/pipelines/github/flexion/ef-cms/39103/workflows/295ca8c3-c7e5-4c18-b84e-0c3f58c99959

**Review by rosiehsmith — APPROVED** [review]

**Review by rachelschneiderman — APPROVED** [review]

**Review by jimlerza — APPROVED** [review]

**Review by mmarcotte — APPROVED** [review]

**Pull request merged**
