### PR TITLE
Devex 1060: s3 documents bucket policy for glue jobs from prod

### PR DESCRIPTION
**Pull request by rosiehsmith**
Add Bucket Policy to dawson.ustaxcourt.gov-documents-prod-us-east-1 through IaC [Trello Card](https://trello.com/c/eQVS5w2z/1060-add-bucket-policy-to-dawsonustaxcourtgov-documents-prod-us-east-1-through-iac)

[CircleCI step ](https://app.circleci.com/pipelines/github/flexion/ef-cms/34987/workflows/ad568e09-3f28-4029-a3b2-90587bd37ec9/jobs/221355/parallel-runs/0/steps/0-113)checking that the policy is created on exp5 when validating the IaC added
[
Circle Workflow](https://app.circleci.com/pipelines/github/flexion/ef-cms/34992/workflows/354460e3-d08b-4360-bdd9-699d4daab89a/jobs/221388) ensuring policy is not added to exp5 when updating the conditional to look for `prod`

### CODE REVIEW

**Review by halprin — COMMENTED** [review]
Any thought about doing this in Terraform?  We can do basic "if" statements in Terraform where it only applies a policy if the environment is `prod` and `us-east-1`.

**Comment by rosiehsmith** [comment]
> Any thought about doing this in Terraform? We can do basic "if" statements in Terraform where it only applies a policy if the environment is `prod` and `us-east-1`.

I'm open to that! I didn't know if creating an exception for one specific environment's region-specific bucket was a good use case to put into Terraform. Want to pair on your suggestion?

**Comment by halprin** [comment]
> > Any thought about doing this in Terraform? We can do basic "if" statements in Terraform where it only applies a policy if the environment is `prod` and `us-east-1`.
> 
> I'm open to that! I didn't know if creating an exception for one specific environment's region-specific bucket was a good use case to put into Terraform. Want to pair on your suggestion?

Yes, I think it would still be a good candidate.  And yeah, let's pair!

**Review by halprin — APPROVED** [review]
Awesome!

**Review by jimlerza — APPROVED** [review]

**Pull request merged**
