### PR TITLE
386: Serve documents from app host.

### LINKED ISSUE #386: Adjust our Cloutfront configuration to allow for pathing to S3 buckets
In order to have a more streamlined approach, obscure the S3 naming conventions that we use for our infrastructure, utilize caching and save on bandwidth costs, we should consider using Cloudfront to act as a CDN URL in front of the PDFs in our buckets. We could consider a subdomain like `docs.dawson.ustaxcourt.gov` or one of the existing API subdomains with a `/docs/` path.

Acceptance Criteria
- [ ] Document endpoints are available at path that falls under the `*.ustaxcourt.gov` domain rather than S3 URLs

Notes
* This would also help resolve an issue with the IRS having to whitelist another URL path in order to programmatically download PDFs

### PR DESCRIPTION
**Pull request by adunkman**
Closes #386.

This serves documents from both the `documents` and `temp-documents` buckets from the application domain: 

- `documents` and its failover are served from `app.stg.ef-cms.ustaxcourt.gov/documents/`.
- `temp-documents` and its failover are served from `app.stg.ef-cms.ustaxcourt.gov/temp-documents/`.

It accomplishes this by: 

- Adding Cloudfront origin groups for the S3 buckets.
- Adding behaviors to route those paths to the related origin groups.
- Adding a lambda to remove this base path from the request before contacting S3. 

A few notes:

- Caching is disabled in Cloudfront, because these requests are signed URLs. 
- The `terraform plan` for this looks good, but I’m worried that the newly added [S3 origins](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#s3-origin-config-arguments) may not like the format of the `domain_name` passed in. I don’t think we’ll know this until it hits the AWS API during a Terraform apply. 
- This includes a new IAM role, so the account-specific deployment step will need to be run.

Pinging @mmarcotte for the final 👍 to accept, but would also like reviews from the Flexion folks here — @ericsorenson to review or delegate, and at least /cc to @sutt0n (thanks for riding along!) and @rachaelparris (thanks for the terraform help!).

### CODE REVIEW

**Review by mmarcotte — APPROVED** [review]
Looks sharp to me. Thank you!

@adunkman -- one question, you said account-specific in your comment, but it appears that IAM change is in fact environment-specific. Just making sure.

**Comment by adunkman** [comment]
Oop, you’re right — environment-specific.

**Review by ericsorenson — APPROVED** [review]

**Review by codyseibert — APPROVED** [review]
seems good!

**Review by sutt0n — APPROVED** [review]

**Comment by adunkman** [comment]
Caught a few tweaks when applying this in the `dev` environment — updated in 4f9bb9ce5aa98908ce830caf7514f098d92bba32. Retagging @mmarcotte for a re-review; once you’re satisfied with the changes we’re good to merge to `staging`. 🚀

**Review by mmarcotte — APPROVED** [review]

**Pull request merged**
