### PR TITLE
9074: Added docketNumberWithSuffix to EligibleCase entity

### PR DESCRIPTION
**Pull request by TomElliottFlexion**
Screen Shot 2021-10-21 at 10 56 11 AM

### CODE REVIEW

**Review by rachelschneiderman — COMMENTED** [review]
Is there a test that could be added that would have caught this bug? Maybe adding an expect to an integration test?

**Comment by TomElliottFlexion** [comment]
Not sure if this _should_ be covered with an integration test. This was a matter of exposing a new attribute on the data structure

**Review by kkoskelin — APPROVED** [review]

**Comment by rachelschneiderman** [comment]
> Not sure if this _should_ be covered with an integration test. This was a matter of exposing a new attribute on the data structure

Generally when I pick up a bug, I try and write a failing test first that covers the bug. IMO this should be covered if it can be by some type of test that would have failed before the solution was explored.

**Review by kkoskelin — APPROVED** [review]

**Review by rachelschneiderman — APPROVED** [review]
Looks great!!!

**Comment by TomElliottFlexion** [comment]
> Not sure if this _should_ be covered with an integration test. This was a matter of exposing a new attribute on the data structure

Upon further discussion, this is _exactly_ the kind of thing that should be covered by an integration test

**Pull request closed without merging**
