### PR TITLE
Dependency Updates Week of 10/10/2022

### PR DESCRIPTION
**Pull request by ujahio**
### This round of updates includes:
- Publishing a new ECR image 2.8.0 **this will require manually running `docker-to-ecr.sh` on the court side** 
- Update Terraform to 1.3.2
- [CI Workflow](https://app.circleci.com/pipelines/github/flexion/ef-cms/38370/workflows/92c6cfc9-7f83-489d-91a1-a00b98ba78e4) with a migration

### Minor package update(s): 
 - @aws-sdk/credential-provider-node
 - @aws-sdk/node-http-handler
 - @aws-sdk/protocol-http
 - @aws-sdk/signature-v4
 - aws-sdk
 - eslint
 - sass-loader
 - esbuild-css-modules-plugin
 - @faker-js/faker
 - csv-parse
 - cypress

### Patch package update(s): 
 - express
 - @babel/preset-env
 - @types/jest
 - eslint-plugin-jest
 - eslint-plugin-react
 - joi
 - eslint-plugin-react

 
### Security audit fixes, secure versions added to resolutions block:
  - None

Task(s) left:
- [x] Publish image to Flexion
- [x] Force Migration to test changes
- [x] Publish image to Court

### CODE REVIEW

**Review by rgoshen — APPROVED** [review]

**Review by rachelschneiderman — COMMENTED** [review]
Was there a deploy with a migration performed on an exp to verify these updates?

**Comment by ujahio** [comment]
> Was there a deploy with a migration performed on an exp to verify these updates?

This PR isn't ready to be reviewed or merged. I've converted it to a draft PR to reflect that. Apologies for the confusion.

**Comment by rachelschneiderman** [comment]
> This PR isn't ready to be reviewed or merged. I've converted it to a draft PR to reflect that. Apologies for the confusion.

Oops, I'm sorry! It was already like that. I missed that!

**Review by TomElliottFlexion — APPROVED** [review]

**Review by jamesobrooks — APPROVED** [review]

**Review by shumway-tm — APPROVED** [review]

**Review by rachelschneiderman — COMMENTED** [review]
I noticed the `wait-for-reindex` step was manually approved. Is there any concern about the updates having broken that step?

**Review by jimlerza — APPROVED** [review]

**Comment by ujahio** [comment]
> I noticed the `wait-for-reindex` step was manually approved. Is there any concern about the updates having broken that step?

@rachelschneiderman I didn't consider the concerns that may have. I can always validate it by forcing migration again

@rachelschneiderman I have forced migration and verified the auto approval occurred with the new updates. Here's the [CI workflow](https://app.circleci.com/pipelines/github/flexion/ef-cms/38370/workflows/92c6cfc9-7f83-489d-91a1-a00b98ba78e4)
cc: @jimlerza

**Comment by rachelschneiderman** [comment]
Thank you Josh!!!

**Pull request merged**
